name: build action
description: the sample build action
runs: 
  using: 'node16'
  steps:
    name: Run markdown lint
    run: |
      npm install remark-cli remark-preset-lint-consistent
      npx remark . --use remark-preset-lint-consistent --frail
